services:
  rts-minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - rts_minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

  rts-minio-init:
    image: minio/mc:latest
    depends_on:
      - rts-minio
    entrypoint: >
      /bin/sh -c "
        sleep 5
        mc alias set myminio http://rts-minio:9000 minioadmin minioadmin
        mc mb myminio/drones || echo "Bucket 'drones' already exists"
        mc policy set public myminio/drones
        echo "Bucket 'drones' created and made public"
      "

  rts-mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - rts_mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
    restart: always

volumes:
  rts_mongo_data:
  rts_minio_data:
